version: '3.8'

services:
  
  postgresql:
    image: postgres:17.2
    container_name: bd-swing
    restart: always
    volumes:
      - ./src/main/resources/db.migration/create-table.sql:/docker-entrypoint-initdb.d/create-table.sql
      - ./src/main/resources/db.migration/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=bd_swing
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5432:5432" 